### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by RamonGebben** [ginpei/html5-youtube.js#2]
It would be really nice if this library could be installed via `npm install`

**Comment by ginpei** [comment]
Good! Please wait a minute.

**Comment by ginpei** [comment]
The name "youtube" is already used. I'm going to change name to "html5-youtube".

**Comment by ginpei** [comment]
OK. Try `$ npm i -S html5-youtube`!

**Comment by RamonGebben** [comment]
Nice using it now!
