### ISSUE TITLE
Can we create a player with a delay?

### ISSUE THREAD

**Issue by onigetoc** [ginpei/html5-youtube.js#45]
I want to create player on the fly and control them.

do you have a minimal test to create a player with like on a button click?
It mean that the querySelector it not yet created because i create my own video control player on action event latter.

In my very early demo, i did a button to destroy the jPlayer control and i want to use the same buttons control the Youtube video with your great script.
https://codepen.io/onigetoc/pen/KXNXqQ?editors=1010

I add a ".yt-player" class on the main control and i'm trying to control the player. if i return back to a non Youtube video i will remove this class.

**Comment by ginpei** [comment]
Here is a minimal demo to create the video when you click a button. It creates an element and activate it on the fly.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>html5-youtube.js</title>
  </head>
  <body>
    <p><button id="create">Create</button></p>
    <script src="html5-youtube.js"></script>
    <script>
document.querySelector('#create').onclick = function(event) {
  var elPlayer = document.createElement('div');
  document.body.appendChild(elPlayer);
  youtube({ el:elPlayer, id:'KFstP0C9sVk' });
}
    </script>
  </body>
</html>
```

Is this what you want to see?

**Comment by onigetoc** [comment]
Yes i think if this is working it will do the trick, i'm trying to create a new player on event or user action.
i also want to create multiple players.

Do it will work if i use jQuery to create player?
I also want to use the example with .on option on play pause ready ect.
like: 

```
var ELplayer = youtube({
    el: elPlayer,
    //        list: "PL6Go6XFhidEAH6LrK-RKxR5xwhdZ0g4vm",
    controls: 0,
    showinfo: 0, // hide Youtube title but show logo
    iv_load_policy: 3,
    rel: 0,
    fs: 0,
    id: videoId
  })
  .on('ready', function (event) {
    //ELplayer.play();
    //alert("ready")
    //alert("ELplayer ready")

    $(document).on('click', '.yt-player.jp-state-paused .jp-play', function () {
        ELplayer.play();
      })
      .on('click', '.yt-player.jp-state-playing .jp-play', function () {
        ELplayer.pause();
      })
      .on('click', '.yt-player .jp-stop', function () {
        //ELplayer.pause();
        //alert("stop Video")
        elPlayer.stopVideo(); // do not work
      });
  })
```

**Comment by ginpei** [comment]
I'm sorry but I'm afraid that I don't get what is your question...

```js
        elPlayer.stopVideo(); // do not work
```

In this case, `elPlayer` should be an HTML element, probably `<div>`, which doesn't have the method `stopVideo()`. I guess what you want to invoke here is something like following:

```js
ELplayer.pause();
ELplayer.currentTime = 0;
```

By the way, "el" means "elements". I use it to express a variable contains an element.

**Comment by onigetoc** [comment]
In the last question i just copied my code, i do not talk about how to stop video since you give me the answer but if or how i can use .on functions on a new created player with user action.

Thank you

**Comment by ginpei** [comment]
> how i can use .on functions on a new created player with user action.

Still I'm confused. How to use `.on` is just use `.on` after creating an instance.

```js
document.querySelector('#create').onclick = function(event) {
  var elPlayer = document.createElement('div')
  document.body.appendChild(elPlayer)
  player = youtube({ el:elPlayer, id:'KFstP0C9sVk' })

  // here you go
  player.on('play', function(event) {
    console.log('play')
  })

  // you may have to consider not to create it twice
}
```

**Comment by onigetoc** [comment]
I think i found out the problem, i want to use it with jPlayer and your script initiate after jPlayer. It should load on dom ready and not when all html and images are loaded. there's no reason to wait for html and images.

https://stackoverflow.com/questions/3698200/window-onload-vs-document-ready
https://developer.mozilla.org/fr/docs/Web/Events/DOMContentLoaded
https://stackoverflow.com/questions/2414750/difference-between-domcontentloaded-and-load-events
http://web.archive.org/web/20150405114023/http://ie.microsoft.com/testdrive/HTML5/DOMContentLoaded/Default.html

**Comment by ginpei** [comment]
OK then I'm going to close this.
