### ISSUE TITLE
Miss some feature functions

### ISSUE THREAD

**Issue by onigetoc** [ginpei/html5-youtube.js#46]
Hi,
Your little Youtube iframe api plugin is really great but it miss some Youtube api iframe functions

1. MISS NEXT & PREVIOUS FUNCTIONS FOR PLAYLIST:
player.previousVideo();
player.nextVideo();
2. MISS STOP FUNCTION: 
player.stopVideo();
3. MISS A SIMPLE SEEKTO FUNCTION:
player.seekTo(60);
4. WRONG VIDEO SIZE OR HEIGHT for 16:9: 
height = 360; (not 390)
width = 640;
http://size43.com/jqueryVideoTool.html
https://calculateaspectratio.com/

**Comment by ginpei** [comment]
The purpose of this library is to handle YouTube videos like HTML5 videos.

> player.previousVideo();
> player.nextVideo();

They are not HTML5 Video API. Could you handle YouTube video list by yourself?

- [HTMLMediaElement - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement)

>  player.stopVideo();

Please use `pause()` and set `currentTime = 0` instead.

>  player.seekTo(60);

Please use `currentTime = 60` as well.

> height = 360; (not 390)
> width = 640;

You can specify size by CSS.

**Comment by ginpei** [comment]
OK then I'm going to close this.
