### ISSUE TITLE
Question about using rel

### ISSUE THREAD

**Issue by oleteacher** [ginpei/html5-youtube.js#48]
This is really a great share, have learned a lot about the YT api, I thank you!

Using the full-player.html file to load some videos for classroom tutorials. Need to activate the rel and have tried to place in script:

rel: false,

If I place rel: false, in it's on script tag right below html5-youtube.js it works, but then the dropdown to load other videos is disabled.

Can you give me tip where to place rel: false, in full-player.html?

Thank you!

**Comment by oleteacher** [comment]
Figure this is a abandoned project so closing.

**Comment by ginpei** [comment]
I cannot see the problem. Just adding `rel: 0` worked on my machine.

```js
var player = window.player = youtube({ el:elPlayer, rel: 0 });
```

![image](https://user-images.githubusercontent.com/355808/134851736-25109035-921c-478e-993b-28c1e63523f5.png)

Could you share more details like your code, OS and browser?

Note that `file://` URL (double-clicking an HTML file) may cause network problem in general.

**Comment by oleteacher** [comment]
Looks like I did not understand. Looked at docs and though it stated "rel: false,". I have now used "rel: 0" in var player line and working great.

Thank you!
