### ISSUE TITLE
autoplay and controls options values should be Numbers when passed to the YT player

### ISSUE THREAD

**Issue by clementoriol** [ginpei/html5-youtube.js#5]
Hi ! 
Started working with your library on a project, and realized controls couldn't be deactivated by passing `{controls: false}` when initalizing the player, like the readme says.

Youtube actually expects Numbers (0, 1 or 2) for everything related to playerVars (source: https://developers.google.com/youtube/player_parameters), and you're currently passing Booleans.

**I forked your project and starting implementing it**, I'd love your feedback and your take on this (and my code) : https://github.com/clementoriol/html5-youtube.js/tree/feature/playerVars

In the future I'll need other playerVars, like `modestbranding` or `showinfo`, so **I'm thinking about implementing all playerVars too, if it's ok with you**.

**Comment by clementoriol** [comment]
Extra note : Since the HTML5 video API uses booleans for `autoplay` and `controls`, those should be allowed for coherence, but they need to be converted to numbers to be passed on the YT players and work properly

**Comment by ginpei** [comment]
OK, I'll fix that to convert if boolean and to accept numbers.

Thank you for reporting!! :satisfied:
