### ISSUE TITLE
Use video example that is available in all countries

### ISSUE THREAD

**Issue by yuvilio** [ginpei/html5-youtube.js#8]
The video example you use isn't available in the US.  You may want to switch to a youtube video that is avalable in all regions so your example will work everywhere.

![sw-0083](https://cloud.githubusercontent.com/assets/128731/11850187/be7e307c-a3f9-11e5-8baf-749265685607.png)

**Comment by ginpei** [comment]
Thank you! I'll do that. The videos are available in both Japan and Canada, so I  didn't realize this matter.

Then do you (or anybody watching here) have any suggestion? We need videos that are legitimate (official version is better), independent from languages (ex: instrumental music) and looks cool (important!).

**Comment by ginpei** [comment]
Is the other one unavailable too?

https://www.youtube.com/watch?v=KFstP0C9sVk

**Comment by yuvilio** [comment]
That video works in the US, yeah.

Here are few other fair use candidates to add to the mix (assuming they're visible in other regions besides US). 

[Detektivbyran](https://www.youtube.com/watch?v=5wLWhSZ1Uvo)

[Eri Sugai](https://www.youtube.com/watch?v=aY2eo8KS6R4)

[Sail - Cello Cover](https://www.youtube.com/watch?v=o0zuU2yYt3Y)

Suggestions by others also welcome. They'll probably be more official than mine.

**Comment by ginpei** [comment]
Detektivbyrån sounds so nice and looks official.

Now I did it. Could you check please?

http://ginpei.github.io/html5-youtube.js/

**Comment by yuvilio** [comment]
All demos now working for me. Closing this one out.  Thanks for the great player.
